import { useEffect, useRef, useState, type Dispatch, type MutableRefObject, type SetStateAction } from 'react'
import { stopCameraStream } from '../camera/cameraService'
import { subscribeToOrientation, type OrientationReading } from '../sensors/orientationService'
import type { PreparedSmartScan } from '../smart-scan/prepareSmartScan'
import type { SpatialDiagnostics, SpatialPose } from '../spatial/spatialTypes'
import type { SmartScanCapabilities, Vector3 } from '../smart-scan/smartScanTypes'
import { ObjectTracker } from '../smart-scan/object-tracking/ObjectTracker'
import { objectTrackingConfig } from '../smart-scan/object-tracking/objectTrackingConfig'
import type { BoundingBox, ObjectTrackingResult } from '../smart-scan/object-tracking/objectTrackingTypes'
import { evaluateFrameQuality, type FrameQualityResult } from '../smart-scan/capture/frameQualityEvaluator'
import { ViewDiversityEvaluator, type ViewSignature } from '../smart-scan/capture/viewDiversityEvaluator'
import type { CapturedFrame, RelativeView, ScanSession } from '../smart-scan/capture/scanSessionTypes'
import { OnnxGraveDetector } from '../ai/grave-detection/OnnxGraveDetector'
import { DetectionStabilizer } from '../ai/grave-detection/DetectionStabilizer'
import { TargetSelector } from '../ai/grave-detection/TargetSelector'
import type { DetectionResult, DetectorDiagnostics, ModelStatus } from '../ai/grave-detection/graveDetectionTypes'
import { RemoteScanPanel } from '../components/RemoteScanPanel'
import { MappingPanel } from '../components/MappingPanel'

type ScanState = 'SEARCHING' | 'OBJECT_LOCK_REQUESTED' | 'LOCKING' | 'LOCKED' | 'CAPTURING' | 'OBJECT_LOST' | 'SCAN_COMPLETE' | 'FAILED'
type SmartScanPageProps = { prepared: PreparedSmartScan; onExit: () => void }
const targetFrameCount = 6

export function SmartScanPage({ prepared, onExit }: SmartScanPageProps) {
  const videoRef = useRef<HTMLVideoElement>(null); const canvasRef = useRef<HTMLCanvasElement>(null)
  const trackerRef = useRef(new ObjectTracker()); const diversityRef = useRef(new ViewDiversityEvaluator()); const timerRef = useRef<number | null>(null); const sessionRef = useRef<ScanSession | null>(null)
  const detectionTimerRef = useRef<number | null>(null); const detectorRef = useRef(new OnnxGraveDetector()); const stabilizerRef = useRef(new DetectionStabilizer()); const selectorRef = useRef(new TargetSelector()); const captureActiveRef = useRef(false)
  const [capabilities, setCapabilities] = useState<SmartScanCapabilities>(prepared.capabilities)
  const [orientation, setOrientation] = useState<OrientationReading>(prepared.capabilities.sensorData.orientation)
  const [position, setPosition] = useState<Vector3 | null>(null); const [pose, setPose] = useState<SpatialPose | null>(prepared.spatialProvider.getPose())
  const [spatialDiagnostics, setSpatialDiagnostics] = useState<SpatialDiagnostics | null>(prepared.spatialDiagnostics); const [scanState, setScanState] = useState<ScanState>('SEARCHING')
  const [tracking, setTracking] = useState<ObjectTrackingResult | null>(null); const [box, setBox] = useState<BoundingBox | null>(null); const [quality, setQuality] = useState<FrameQualityResult | null>(null); const [session, setSession] = useState<ScanSession | null>(null); const [message, setMessage] = useState('Наведите камеру на объект')
  const [modelStatus, setModelStatus] = useState<ModelStatus>('NOT_LOADED'); const [detectorDiagnostics, setDetectorDiagnostics] = useState<DetectorDiagnostics>(detectorRef.current.getDiagnostics()); const [lastDetection, setLastDetection] = useState<DetectionResult | null>(null); const [remoteCaptureActive, setRemoteCaptureActive] = useState(false); const [mappingOpen, setMappingOpen] = useState(false)
  const [remoteOpen, setRemoteOpen] = useState(false)

  useEffect(() => {
    const video = videoRef.current
    if (video && prepared.cameraStream) { video.srcObject = prepared.cameraStream; void video.play().catch(() => undefined) }
    const unsubscribeOrientation = subscribeToOrientation(setOrientation)
    const unsubscribePose = prepared.spatialProvider.subscribePose((nextPose) => { setPose(nextPose); setPosition(nextPose?.position ?? null) })
    const unsubscribeDiagnostics = prepared.spatialProvider.subscribeDiagnostics((diagnostics) => updateSpatialDiagnostics(diagnostics, setSpatialDiagnostics, setCapabilities))
    void detectorRef.current.load().then(() => { setModelStatus('READY'); setMessage('Ищу захоронение...'); scheduleDetection(detectionTimerRef, detectFrame) }).catch(() => { setModelStatus(detectorRef.current.getStatus()); setMessage('Модуль распознавания захоронений пока недоступен'); setDetectorDiagnostics(detectorRef.current.getDiagnostics()) })
    return () => { unsubscribeOrientation(); unsubscribePose(); unsubscribeDiagnostics(); stopSampling(timerRef); stopSampling(detectionTimerRef); captureActiveRef.current = false; void detectorRef.current.unload(); trackerRef.current.reset(); diversityRef.current.reset(); if (video) video.srcObject = null; void prepared.spatialProvider.stop(); if (prepared.cameraStream && prepared.spatialProvider.mode === 'sensor-limited') stopCameraStream(prepared.cameraStream) }
  }, [prepared])

  const detectFrame = () => {
    if (captureActiveRef.current || detectorRef.current.getStatus() !== 'READY' || !videoRef.current) return
    const image = readFrame(videoRef.current, canvasRef.current)
    if (!image) { scheduleDetection(detectionTimerRef, detectFrame); return }
    void detectorRef.current.detect({ image }).then((detections) => {
      const selected = selectorRef.current.select(detections); const stable = stabilizerRef.current.update(detections); const candidate = stable ?? selected
      setLastDetection(candidate); setDetectorDiagnostics(detectorRef.current.getDiagnostics(detections.length))
      if (candidate) { setBox(candidate.box); setMessage(stable ? 'Объект определён' : 'Объект найден') }
      if (stable && !captureActiveRef.current) {
        const result = trackerRef.current.lock(stable.box, image)
        if (result.featureCount >= objectTrackingConfig.minFeatures) { captureActiveRef.current = true; setTracking(result); setScanState('CAPTURING'); setMessage('Сканирование началось'); sessionRef.current = createSession(prepared.spatialProvider.mode); sessionRef.current.detectorModelVersion = detectorRef.current.getManifest()?.version; setSession(sessionRef.current); stopSampling(detectionTimerRef); scheduleSample(timerRef, sampleFrame) }
      }
    }).catch((error) => { setModelStatus(detectorRef.current.getStatus()); setDetectorDiagnostics({ ...detectorRef.current.getDiagnostics(), error: error instanceof Error ? error.message : 'Detector inference failed.' }) }).finally(() => { if (!captureActiveRef.current) scheduleDetection(detectionTimerRef, detectFrame) })
  }

  const repeat = () => { stopSampling(timerRef); trackerRef.current.reset(); diversityRef.current.reset(); sessionRef.current = null; setSession(null); setBox(null); setTracking(null); setQuality(null); setScanState('SEARCHING'); setMessage('Наведите камеру на объект') }
  const startRemoteCapture = () => { const next = createSession(prepared.spatialProvider.mode); next.detectorModelVersion = 'pc-only'; sessionRef.current = next; setSession({ ...next }); captureActiveRef.current = true; setRemoteCaptureActive(true); setScanState('CAPTURING'); setMessage('Медленно снимайте объект с разных сторон'); scheduleSample(timerRef, captureRemoteFrame) }
  const captureRemoteFrame = () => { const video = videoRef.current; if (!video || !captureActiveRef.current) return; void captureUnclassifiedFrame(video).then((captured) => { if (!captured || !sessionRef.current || sessionRef.current.status !== 'active') return; sessionRef.current.frames.push(captured); sessionRef.current.acceptedFrames += 1; sessionRef.current.candidateFrames += 1; setSession({ ...sessionRef.current }); setMessage(`Кадр ${sessionRef.current.frames.length}/${targetFrameCount} сохранён`); if (sessionRef.current.frames.length >= targetFrameCount) { stopSampling(timerRef); captureActiveRef.current = false; setRemoteCaptureActive(false); sessionRef.current.status = 'complete'; sessionRef.current.completedAt = Date.now(); setSession({ ...sessionRef.current }); setScanState('SCAN_COMPLETE'); setMessage('Кадры готовы к отправке на ПК') } else scheduleSample(timerRef, captureRemoteFrame) }) }
  const finish = () => { stopSampling(timerRef); if (sessionRef.current) sessionRef.current.status = 'cancelled'; onExit() }
  const sampleFrame = () => {
    const video = videoRef.current; if (!video || !captureActiveRef.current) return
    const image = readFrame(video, canvasRef.current); if (!image) { scheduleSample(timerRef, sampleFrame); return }
    const result = trackerRef.current.update(image); setTracking(result); setBox(result.box)
    if (result.state === 'LOST') { captureActiveRef.current = false; stabilizerRef.current.reset(); selectorRef.current.reset(); setScanState('OBJECT_LOST'); setMessage('Верните памятник в кадр'); scheduleDetection(detectionTimerRef, detectFrame); return }
    if (result.state === 'WEAK' || result.state === 'RECOVERING') { setMessage('Держите объект в рамке'); scheduleSample(timerRef, sampleFrame); return }
    setScanState('CAPTURING'); const frameQuality = evaluateFrameQuality(image, result.box, result); setQuality(frameQuality)
    if (sessionRef.current) { sessionRef.current.candidateFrames += 1; setSession({ ...sessionRef.current }) }
    if (!frameQuality.accepted) { if (sessionRef.current) { sessionRef.current.rejectedFrames += 1; sessionRef.current.lastRejectReason = frameQuality.rejectReason }; setMessage(qualityMessage(frameQuality.rejectReason)); scheduleSample(timerRef, sampleFrame); return }
    const signature = createSignature(result.box!, orientation, pose); const diversity = diversityRef.current.evaluate(signature)
    if (!diversity.accepted) { if (sessionRef.current) { sessionRef.current.rejectedFrames += 1; sessionRef.current.lastRejectReason = 'Similar view' }; setMessage('Измените угол съёмки'); scheduleSample(timerRef, sampleFrame); return }
    void captureFrame(video, result, frameQuality, signature, lastDetection?.confidence ?? 0).then((captured) => {
      if (!captured || !sessionRef.current) return
      sessionRef.current.frames.push(captured); sessionRef.current.acceptedFrames += 1; sessionRef.current.viewDiversityScore = diversity.score; diversityRef.current.add(signature, diversity.score); setSession({ ...sessionRef.current })
      if (sessionRef.current.frames.length >= targetFrameCount) { sessionRef.current.status = 'complete'; sessionRef.current.completedAt = Date.now(); setSession({ ...sessionRef.current }); setScanState('SCAN_COMPLETE'); setMessage('Скан завершён') } else setMessage('Медленно перемещайте телефон вокруг объекта')
    }).finally(() => { if (sessionRef.current?.status === 'active') scheduleSample(timerRef, sampleFrame) })
  }

  const trackingLabel = spatialDiagnostics?.mode === 'vision' ? 'VISION' : capabilities.trackingState; const metricTracking = spatialDiagnostics?.mode.startsWith('xr-') && capabilities.trackingState === 'ACTIVE'
  return <main className="smart-scan-page">
    {prepared.cameraStream && <video ref={videoRef} className="smart-scan-camera" autoPlay muted playsInline aria-label="Smart Scan camera" />}<canvas ref={canvasRef} className="smart-scan-sampler" /><div className="smart-scan-shade" />
    <div className="smart-scan-hud"><header className="scan-topbar"><div><p className="scan-kicker">Cemetery Mapper</p><h1>Smart Scan</h1></div><span className={`spatial-pill spatial-${capabilities.trackingState.toLowerCase()}`}>Spatial tracking: {trackingLabel}</span></header>
      <section className="scan-diagnostics" aria-label="Smart Scan status"><span>State: {scanState}</span><span>Object: {tracking?.state ?? 'INITIALIZING'}</span><span>Features: {tracking?.featureCount ?? 0}</span><span>Confidence: {tracking ? `${Math.round(tracking.confidence * 100)}%` : '—'}</span><span>Spatial: {spatialDiagnostics?.scaleStatus ?? 'UNSCALED'}</span></section>
      <div className="scan-reticle" aria-hidden="true">+</div>{box && scanState !== 'SEARCHING' && scanState !== 'SCAN_COMPLETE' && <div className={`object-box object-box-${tracking?.state.toLowerCase() ?? 'initializing'}`} style={{ left: `${box.x * 100}%`, top: `${box.y * 100}%`, width: `${box.width * 100}%`, height: `${box.height * 100}%` }}><span>Selected object</span></div>}
      {metricTracking && <PositionHud position={position} distance={distanceFromOrigin(pose)} />}{spatialDiagnostics?.mode === 'vision' && <VisionTrajectoryHud position={spatialDiagnostics.relativePosition} />}<div className="scan-message">{message}</div>
      {!remoteCaptureActive && scanState !== 'SCAN_COMPLETE' && <><button className="capture-object-button" type="button" onClick={() => setMappingOpen(true)}>START MAPPING</button><button className="capture-object-button capture-object-button-secondary" type="button" onClick={startRemoteCapture}>QUICK PC SCAN</button></>}
      {scanState === 'CAPTURING' && <div className="capture-progress"><strong>{session?.frames.length ?? 0} / {targetFrameCount}</strong><span>Медленно перемещайте телефон вокруг объекта</span><span>{'● '.repeat(session?.frames.length ?? 0)}{'○ '.repeat(targetFrameCount - (session?.frames.length ?? 0))}</span></div>}
      {scanState === 'SCAN_COMPLETE' && <ScanComplete session={session} onRepeat={repeat} onDone={onExit} onSend={() => setRemoteOpen(true)} />}<SpatialDiagnosticsPanel capabilities={capabilities} diagnostics={spatialDiagnostics} tracking={tracking} quality={quality} session={session} modelStatus={modelStatus} detectorDiagnostics={detectorDiagnostics} />
      {remoteOpen && session && <RemoteScanPanel frames={session.frames.map((frame) => frame.image)} onClose={() => setRemoteOpen(false)} />}
      {mappingOpen && <MappingPanel video={videoRef.current} onClose={() => setMappingOpen(false)} />}
      <footer className="scan-footer"><p>{scanState === 'OBJECT_LOST' ? 'Верните памятник в кадр' : 'Камера автоматически ищет объект'}</p><button className="finish-button" type="button" onClick={finish}>Finish</button></footer>
    </div></main>
}

function ScanComplete({ session, onRepeat, onDone, onSend }: { session: ScanSession | null; onRepeat: () => void; onDone: () => void; onSend: () => void }) { return <section className="scan-complete"><h2>СКАН ЗАВЕРШЁН</h2><p>Получено {session?.frames.length ?? 0} хороших ракурсов</p><div className="capture-thumbnails">{session?.frames.map((frame) => <img key={frame.id} src={URL.createObjectURL(frame.image)} alt="Captured view" />)}</div><button type="button" onClick={onSend}>ОТПРАВИТЬ НА ПК</button><button type="button" onClick={onRepeat}>ПОВТОРИТЬ</button><button type="button" onClick={onDone}>ГОТОВО</button></section> }
function SpatialDiagnosticsPanel({ capabilities, diagnostics, tracking, quality, session, modelStatus, detectorDiagnostics }: { capabilities: SmartScanCapabilities; diagnostics: SpatialDiagnostics | null; tracking: ObjectTrackingResult | null; quality: FrameQualityResult | null; session: ScanSession | null; modelStatus: ModelStatus; detectorDiagnostics: DetectorDiagnostics }) { return <details className="xr-diagnostics smart-scan-dev-diagnostics"><summary>Developer diagnostics</summary><div className="diagnostics-content"><span>Scan: {session?.status ?? 'active'}</span><span>Object: {tracking?.state ?? 'INITIALIZING'}</span><span>Object features: {tracking?.featureCount ?? 0}</span><span>Object confidence: {tracking ? `${Math.round(tracking.confidence * 100)}%` : '—'}</span><span>Detector backend: {detectorDiagnostics.backend ?? '—'}</span><span>Model: {modelStatus}</span><span>Inference: {detectorDiagnostics.inferenceMs.toFixed(1)} ms / {detectorDiagnostics.detectorFps.toFixed(1)} FPS</span><span>Detections: {detectorDiagnostics.detections}</span><span>Candidate frames: {session?.candidateFrames ?? 0}</span><span>Accepted frames: {session?.acceptedFrames ?? 0}</span><span>Rejected frames: {session?.rejectedFrames ?? 0}</span><span>Current quality: {quality ? `${Math.round(quality.score * 100)}%` : '—'}</span><span>Last reject: {session?.lastRejectReason ?? quality?.rejectReason ?? '—'}</span><span>View diversity: {session?.viewDiversityScore != null ? `${Math.round(session.viewDiversityScore * 100)}%` : '—'}</span><span>Spatial: {diagnostics?.provider ?? '—'} / {diagnostics?.accuracy?.level ?? '—'}</span><span>Scale: {diagnostics?.scaleStatus ?? 'UNSCALED'}</span><span>GPS quality: {getGpsQuality(capabilities.sensorData.location?.accuracy)}</span></div></details> }
async function captureFrame(video: HTMLVideoElement, tracking: ObjectTrackingResult, quality: FrameQualityResult, signature: ViewSignature, detectorConfidence: number): Promise<CapturedFrame | null> { if (!tracking.box) return null; const canvas = document.createElement('canvas'); const scale = Math.min(1920 / Math.max(video.videoWidth, video.videoHeight), 1); canvas.width = Math.max(1, Math.round(video.videoWidth * scale)); canvas.height = Math.max(1, Math.round(video.videoHeight * scale)); const context = canvas.getContext('2d'); if (!context) return null; context.drawImage(video, 0, 0, canvas.width, canvas.height); const image = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.88)); if (!image) return null; return { id: crypto.randomUUID(), timestamp: Date.now(), image, width: canvas.width, height: canvas.height, quality, graveBox: tracking.box, detectorConfidence, trackerConfidence: tracking.confidence, ocrCandidateScore: quality.score, relativeView: classifyView(signature), viewSignature: signature } }
async function captureUnclassifiedFrame(video: HTMLVideoElement): Promise<CapturedFrame | null> { const canvas = document.createElement('canvas'); const scale = Math.min(1920 / Math.max(video.videoWidth, video.videoHeight), 1); canvas.width = Math.max(1, Math.round(video.videoWidth * scale)); canvas.height = Math.max(1, Math.round(video.videoHeight * scale)); const context = canvas.getContext('2d'); if (!context) return null; context.drawImage(video, 0, 0, canvas.width, canvas.height); const image = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.9)); if (!image) return null; const graveBox = { x: 0, y: 0, width: 1, height: 1 }; const quality: FrameQualityResult = { score: 1, sharpness: 1, brightness: 1, exposureQuality: 1, objectVisibility: 1, trackingConfidence: 0, accepted: true }; return { id: crypto.randomUUID(), timestamp: Date.now(), image, width: canvas.width, height: canvas.height, quality, graveBox, detectorConfidence: 0, trackerConfidence: 0, ocrCandidateScore: 0, relativeView: 'OTHER' } }
function readFrame(video: HTMLVideoElement, canvas: HTMLCanvasElement | null) { if (!canvas || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA) return null; canvas.width = objectTrackingConfig.sampleWidth; canvas.height = objectTrackingConfig.sampleHeight; const context = canvas.getContext('2d', { willReadFrequently: true }); if (!context) return null; context.drawImage(video, 0, 0, canvas.width, canvas.height); return context.getImageData(0, 0, canvas.width, canvas.height) }
function createSession(mode: 'xr-high' | 'xr-standard' | 'vision' | 'sensor-limited'): ScanSession { return { id: crypto.randomUUID(), startedAt: Date.now(), spatialMode: mode.startsWith('xr-') ? 'ar' : 'limited', frames: [], candidateFrames: 0, acceptedFrames: 0, rejectedFrames: 0, detectorModelVersion: 'unknown', lifecycle: 'SCANNING', status: 'active' } }
function createSignature(box: BoundingBox, orientation: OrientationReading, pose: SpatialPose | null): ViewSignature { return { box, orientation: { alpha: orientation.alpha, beta: orientation.beta, gamma: orientation.gamma }, position: pose?.position ?? null } }
function classifyView(signature: ViewSignature): RelativeView { const dx = signature.box.x + signature.box.width / 2 - 0.5; const dy = signature.box.y + signature.box.height / 2 - 0.5; if (Math.abs(dx) < 0.08 && Math.abs(dy) < 0.08) return 'CENTER'; if (Math.abs(dx) > Math.abs(dy)) return dx < 0 ? 'LEFT' : 'RIGHT'; return dy < 0 ? 'HIGH' : 'LOW' }
function distanceFromOrigin(pose: SpatialPose | null) { return pose ? Math.hypot(pose.position.x, pose.position.y, pose.position.z) : null }
function qualityMessage(reason?: string) { return reason === 'Too dark' ? 'Слишком темно' : reason === 'Strong overexposure' ? 'Сильный пересвет' : reason === 'Move the phone more slowly' ? 'Двигайте телефон медленнее' : 'Удерживайте объект в рамке' }
function updateSpatialDiagnostics(diagnostics: SpatialDiagnostics, setDiagnostics: (value: SpatialDiagnostics) => void, setCapabilities: Dispatch<SetStateAction<SmartScanCapabilities>>) { setDiagnostics(diagnostics); setCapabilities((current) => ({ ...current, trackingState: diagnostics.trackingState, spatialMode: diagnostics.mode.startsWith('xr-') && diagnostics.trackingState === 'ACTIVE' ? 'ar' : 'limited', referenceSpaceType: diagnostics.referenceSpaceType ?? null, xrSessionActive: diagnostics.xrSessionActive ?? false, xrPoseActive: diagnostics.xrPoseActive ?? false, xrFrames: diagnostics.xrFrames ?? 0, trackingFrames: diagnostics.trackingFrames ?? 0, lastXRFrameAt: diagnostics.lastXRFrameAt ?? null, webglStatus: diagnostics.webglStatus ?? 'ERROR', xrCompatibleGL: diagnostics.xrCompatibleGL ?? false, baseLayerActive: diagnostics.baseLayerActive ?? false, xrVisibility: (diagnostics.xrVisibility as SmartScanCapabilities['xrVisibility']) ?? 'unknown', xrFrameLoopError: diagnostics.xrFrameLoopError ?? null })) }
function getGpsQuality(accuracy: number | undefined) { return accuracy == null ? 'UNAVAILABLE' : accuracy <= 10 ? 'GOOD' : accuracy <= 30 ? 'POOR' : 'UNUSABLE' }
function stopSampling(timerRef: MutableRefObject<number | null>) { if (timerRef.current !== null) window.clearTimeout(timerRef.current); timerRef.current = null }
function scheduleSample(timerRef: MutableRefObject<number | null>, sample: () => void) { stopSampling(timerRef); timerRef.current = window.setTimeout(sample, 120) }
function scheduleDetection(timerRef: MutableRefObject<number | null>, detect: () => void) { stopSampling(timerRef); timerRef.current = window.setTimeout(detect, 333) }
function PositionHud({ position, distance }: { position: Vector3 | null; distance: number | null }) { return <div className="position-hud"><strong>Position</strong><span>X: {position ? `${position.x.toFixed(2)} m` : 'Unavailable'}</span><span>Y: {position ? `${position.y.toFixed(2)} m` : 'Unavailable'}</span><span>Z: {position ? `${position.z.toFixed(2)} m` : 'Unavailable'}</span><span>From start: {distance == null ? '—' : `${distance.toFixed(2)} m`}</span></div> }
function VisionTrajectoryHud({ position }: { position?: Vector3 }) { return <div className="position-hud vision-position-hud"><strong>Relative trajectory</strong><span>VX: {position?.x.toFixed(4) ?? '—'}</span><span>VY: {position?.y.toFixed(4) ?? '—'}</span><span>VZ: {position?.z.toFixed(4) ?? '—'}</span><span>Scale: UNSCALED</span></div> }
