import { useEffect, useRef, useState, type RefObject } from 'react'
import * as THREE from 'three'
import type { SpatialPose, SpatialTrackingState } from '../spatial/spatialTypes'
import { LiveMappingController } from '../live-mapping/LiveMappingController'
import type { LiveMapSnapshot } from '../live-mapping/liveMappingTypes'

type ViewMode = 'CAMERA' | 'LIVE_3D' | 'SPLIT'
export function LiveWorldMapPanel({ videoRef, pose, trackingState, onClose, onSingleView }: { videoRef: RefObject<HTMLVideoElement | null>; pose: SpatialPose | null; trackingState: SpatialTrackingState; onClose: () => void; onSingleView: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const viewVideoRef = useRef<HTMLVideoElement>(null); const controllerRef = useRef(new LiveMappingController()); const [snapshot, setSnapshot] = useState<LiveMapSnapshot>({ positions: new Float32Array(), colors: new Float32Array(), voxels: 0, keyframes: 0, bounds: null, depthFps: 0, fusionFps: 0, tracking: 'LIMITED', pose: null }); const [mode, setMode] = useState<ViewMode>('SPLIT'); const [status, setStatus] = useState('Инициализация…'); const [error, setError] = useState<string | null>(null)
  useEffect(() => { const source = videoRef.current; const target = viewVideoRef.current; if (source?.srcObject && target) { target.srcObject = source.srcObject; void target.play().catch(() => undefined) } return () => { if (target) target.srcObject = null } }, [videoRef])
  useEffect(() => { let cancelled = false; void controllerRef.current.start().then(() => { if (!cancelled) setStatus('Карта строится…') }).catch((cause) => { if (!cancelled) { setError(cause instanceof Error ? cause.message : 'Depth model unavailable'); setStatus('Depth unavailable') } }); return () => { cancelled = true; controllerRef.current.stop() } }, [])
  useEffect(() => { if (error) return; let cancelled = false; const tick = async () => { const video = videoRef.current; if (video) { const next = await controllerRef.current.process(video, pose, mapTracking(trackingState)); if (!cancelled) setSnapshot(next) } if (!cancelled) window.setTimeout(tick, 650) }; void tick(); return () => { cancelled = true } }, [error, pose, trackingState, videoRef])
  useEffect(() => { if (snapshot.voxels === 0 || !canvasRef.current) return; return renderMap(canvasRef.current, snapshot) }, [snapshot])
  const mapClass = mode === 'CAMERA' ? 'live-map-camera-only' : mode === 'LIVE_3D' ? 'live-map-3d-only' : 'live-map-split'
  return <section className={`remote-scan-panel live-world-map-panel ${mapClass}`}><header><div><p className="scan-kicker">LIVE WORLD MAP</p><h2>Живая 3D-карта</h2></div><button className="remote-close" type="button" onClick={onClose}>Close</button></header><div className="live-map-status">{status}</div>{error && <p className="remote-error">{error}</p>}<div className="live-map-views"><video className="live-map-video" ref={viewVideoRef} autoPlay muted playsInline /><canvas className="live-map-canvas" ref={canvasRef} /></div><div className="live-map-metrics"><span>Tracking: {trackingState}</span><span>Depth: {error ? 'UNAVAILABLE' : 'MONOCULAR'}</span><span>Map points: {snapshot.voxels.toLocaleString()}</span><span>Keyframes: {snapshot.keyframes}</span><span>Depth FPS: {snapshot.depthFps.toFixed(1)}</span><span>Fusion FPS: {snapshot.fusionFps.toFixed(1)}</span><span>Scale: {pose?.metricScaleAvailable ? 'METRIC' : 'RELATIVE'}</span><span>Coverage: {snapshot.bounds ? 'GROWING' : 'EMPTY'}</span></div><div className="single-view-controls"><button type="button" onClick={() => setMode('CAMERA')} aria-pressed={mode === 'CAMERA'}>CAMERA</button><button type="button" onClick={() => setMode('LIVE_3D')} aria-pressed={mode === 'LIVE_3D'}>LIVE 3D</button><button type="button" onClick={() => setMode('SPLIT')} aria-pressed={mode === 'SPLIT'}>SPLIT</button><button type="button" onClick={onSingleView}>SINGLE VIEW PREVIEW</button></div><p className="remote-note">Новые точки добавляются только при наличии реальной camera pose. При потере tracking карта сохраняется, fusion приостанавливается.</p></section>
}
function mapTracking(state: SpatialTrackingState): LiveMapSnapshot['tracking'] { return state === 'ACTIVE' ? 'GOOD' : state === 'LOST' ? 'LOST' : state === 'LIMITED' ? 'LIMITED' : 'WEAK' }
function renderMap(canvas: HTMLCanvasElement, snapshot: LiveMapSnapshot): () => void { const renderer = new THREE.WebGLRenderer({ canvas, antialias: true }); const scene = new THREE.Scene(); scene.background = new THREE.Color('#101615'); const camera = new THREE.PerspectiveCamera(60, 1, 0.01, 100); camera.position.set(0, 0, 2.5); const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position', new THREE.BufferAttribute(snapshot.positions, 3)); geometry.setAttribute('color', new THREE.BufferAttribute(snapshot.colors, 3)); const points = new THREE.Points(geometry, new THREE.PointsMaterial({ size: 0.025, vertexColors: true })); scene.add(points); const resize = () => { const w = canvas.clientWidth || 320; const h = canvas.clientHeight || 240; renderer.setSize(w, h, false); camera.aspect = w / h; camera.updateProjectionMatrix() }; resize(); window.addEventListener('resize', resize); let frame = 0; const loop = () => { renderer.render(scene, camera); frame = requestAnimationFrame(loop) }; loop(); return () => { cancelAnimationFrame(frame); window.removeEventListener('resize', resize); geometry.dispose(); points.material.dispose(); renderer.dispose() } }
