import { useEffect, useRef, useState } from 'react'
import { getRemoteScanApiUrl } from '../api/remoteScanService'
import { sendMappingFrame, startMapping, stopMapping, type MappingTelemetry } from '../api/mappingService'
import { SparseMapViewer } from './SparseMapViewer'
type Props = { video: HTMLVideoElement | null; onClose: () => void }
export function MappingPanel({ video, onClose }: Props) {
  const [telemetry, setTelemetry] = useState<MappingTelemetry | null>(null); const [error, setError] = useState<string | null>(null); const [running, setRunning] = useState(false); const sessionRef = useRef<string | null>(null); const timerRef = useRef<number | null>(null); const busyRef = useRef(false)
  const apiUrl = getRemoteScanApiUrl()
  const stop = async () => { if (timerRef.current) window.clearInterval(timerRef.current); if (sessionRef.current) await stopMapping(apiUrl, sessionRef.current).catch(() => undefined); setRunning(false) }
  const capture = async () => { if (!video || !sessionRef.current || busyRef.current || video.readyState < 2) return; busyRef.current = true; const canvas = document.createElement('canvas'); const scale = Math.min(960 / Math.max(video.videoWidth, video.videoHeight), 1); canvas.width = Math.max(1, Math.round(video.videoWidth * scale)); canvas.height = Math.max(1, Math.round(video.videoHeight * scale)); const context = canvas.getContext('2d'); if (!context) return; context.drawImage(video, 0, 0, canvas.width, canvas.height); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.72)); if (blob) { try { setTelemetry(await sendMappingFrame(apiUrl, sessionRef.current, blob)) } catch (e) { setError(e instanceof Error ? e.message : 'Ошибка передачи кадра') } } busyRef.current = false }
  const start = async () => { try { const result = await startMapping(apiUrl); sessionRef.current = result.sessionId; setRunning(true); timerRef.current = window.setInterval(() => void capture(), 900) } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось запустить mapping') } }
  useEffect(() => { void start(); return () => { if (timerRef.current) window.clearInterval(timerRef.current) } }, [])
  return <section className="mapping-panel"><header><div><p className="scan-kicker">CONTINUOUS MAPPING</p><h2>Building cemetery map</h2></div><button className="remote-close" onClick={() => { void stop(); onClose() }}>Close</button></header>{!running && !error && <p className="remote-note">Подключение к компьютеру…</p>}{running && <><p className="remote-note">Телефон автоматически передаёт ключевые кадры на ПК. Медленно идите вперёд и поворачивайте камеру.</p><SparseMapViewer points={telemetry?.points ?? []} /><div className="mapping-stats"><strong>Frames {telemetry?.frame ?? 0}</strong><span>Features {telemetry?.features ?? 0}</span><span>Matches {telemetry?.matches ?? 0}</span><span>3D points {telemetry?.mapPoints ?? 0}</span><span>Pose {telemetry ? `${telemetry.pose.x.toFixed(3)}, ${telemetry.pose.y.toFixed(3)}, ${telemetry.pose.z.toFixed(3)}` : '—'}</span></div><button className="remote-action" onClick={() => void stop()}>STOP MAPPING</button></>}{error && <p className="remote-error">{error}</p>}</section>
}
