import { useEffect, useRef, useState, type RefObject } from 'react'
import { getRemoteScanApiUrl } from '../api/remoteScanService'
import { sendMappingFrame, startMapping, stopMapping, type MappingTelemetry } from '../api/mappingService'
import type { SpatialPose } from '../spatial/spatialTypes'
import { SparseMapViewer } from './SparseMapViewer'

export function MappingPanel({ videoRef, onClose, pose }: { videoRef: RefObject<HTMLVideoElement | null>; onClose: () => void; pose?: SpatialPose | null }) {
  const [telemetry, setTelemetry] = useState<MappingTelemetry | null>(null); const [error, setError] = useState<string | null>(null); const [running, setRunning] = useState(false); const sessionRef = useRef<string | null>(null); const timerRef = useRef<number | null>(null); const busyRef = useRef(false); const apiUrl = getRemoteScanApiUrl()
  const stop = async () => { if (timerRef.current) window.clearInterval(timerRef.current); if (sessionRef.current) await stopMapping(apiUrl, sessionRef.current).catch(() => undefined); setRunning(false) }
  const capture = async () => { const video = videoRef.current; if (!video || !pose || !sessionRef.current || busyRef.current || video.readyState < 2) return; busyRef.current = true; const canvas = document.createElement('canvas'); const scale = Math.min(960 / Math.max(video.videoWidth, video.videoHeight), 1); canvas.width = Math.max(1, Math.round(video.videoWidth * scale)); canvas.height = Math.max(1, Math.round(video.videoHeight * scale)); const context = canvas.getContext('2d'); if (!context) { busyRef.current = false; return }; context.drawImage(video, 0, 0, canvas.width, canvas.height); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.72)); if (blob) { try { const cameraPose = { position: [pose.position.x, pose.position.y, pose.position.z] as [number, number, number], quaternion: [pose.orientation.x, pose.orientation.y, pose.orientation.z, pose.orientation.w] as [number, number, number, number], confidence: 0.8, method: pose.source.toUpperCase(), scale: pose.metricScaleAvailable ? 'METRIC' : 'RELATIVE' }; setTelemetry(await sendMappingFrame(apiUrl, sessionRef.current, blob, cameraPose)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'PC depth mapping failed') } } busyRef.current = false }
  const start = async () => { try { const result = await startMapping(apiUrl); sessionRef.current = result.sessionId; setRunning(true); timerRef.current = window.setInterval(() => void capture(), 900) } catch (cause) { setError(cause instanceof Error ? cause.message : 'PC mapping failed to start') } }
  useEffect(() => { void start(); return () => { if (timerRef.current) window.clearInterval(timerRef.current) } }, [])
  return <section className="mapping-panel"><header><div><p className="scan-kicker">LIVE WORLD MAP</p><h2>Живая 3D-карта</h2></div><button className="remote-close" type="button" onClick={() => { void stop(); onClose() }}>Close</button></header>{!pose && <p className="remote-error">POSITION_TRACKING_REQUIRED: real camera pose is unavailable.</p>}{!running && !error && <p className="remote-note">Подключение к компьютеру…</p>}{running && <><p className="remote-note">Кадры и pose отправляются на компьютер. Depth и voxel fusion выполняются только на компьютере.</p><SparseMapViewer points={telemetry?.points ?? []} /><div className="mapping-stats"><strong>Frames {telemetry?.frame ?? 0}</strong><span>Depth points {telemetry?.mapPoints ?? 0}</span><span>Scale {pose?.metricScaleAvailable ? 'METRIC' : 'RELATIVE'}</span></div><button className="remote-action" type="button" onClick={() => void stop()}>STOP MAPPING</button></>}{error && <p className="remote-error">{error}</p>}</section>
}
