import { createElement, useEffect, useMemo, useState, type RefObject } from 'react'
import { getRemoteScanApiUrl, getRemoteScanJob, submitRemoteScan, type RemoteScanJob } from '../api/remoteScanService'
export function QuickObjectScanPanel({ videoRef, onClose }: { videoRef: RefObject<HTMLVideoElement | null>; onClose: () => void }) {
  const [job, setJob] = useState<RemoteScanJob | null>(null); const [error, setError] = useState<string | null>(null); const [preview, setPreview] = useState(''); const apiUrl = getRemoteScanApiUrl()
  const capture = async () => { const video = videoRef.current; if (!video || video.readyState < 2) { setError('Камера ещё не готова'); return } const canvas = document.createElement('canvas'); const scale = Math.min(1280 / Math.max(video.videoWidth, video.videoHeight), 1); canvas.width = Math.max(1, Math.round(video.videoWidth * scale)); canvas.height = Math.max(1, Math.round(video.videoHeight * scale)); const context = canvas.getContext('2d'); if (!context) return; context.drawImage(video, 0, 0, canvas.width, canvas.height); const blob = await new Promise<Blob | null>((resolve) => canvas.toBlob(resolve, 'image/jpeg', 0.88)); if (!blob) return; setPreview(URL.createObjectURL(blob)); try { const result = await submitRemoteScan([blob], apiUrl); setJob({ jobId: result.jobId, status: 'queued', progress: 0 }) } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось отправить снимок на ПК') } }
  useEffect(() => { void capture() }, [])
  useEffect(() => { if (!job || job.status === 'completed' || job.status === 'failed') return; const timer = window.setInterval(() => { void getRemoteScanJob(job.jobId, apiUrl).then(setJob).catch((e) => setError(e instanceof Error ? e.message : 'Ошибка связи с ПК')) }, 1000); return () => window.clearInterval(timer) }, [job, apiUrl])
  const object = job?.objects?.[0]; const image = useMemo(() => object?.imageUrl || preview, [object, preview])
  return <section className="remote-scan-panel"><header><div><p className="scan-kicker">QUICK 3D SCAN</p><h2>Object reconstruction</h2></div><button className="remote-close" onClick={onClose}>Close</button></header>{!object && !error && <p className="remote-note">Снимок отправлен на ПК. Построение приблизительной 3D-модели: {job?.progress ?? 0}%</p>}{error && <p className="remote-error">{error}</p>}{object && <><p className="remote-note">Готово. Модель построена по одному снимку.</p><div className="remote-result"><div className="mask-preview"><img src={image} alt="Captured object" /><img className="mask-layer" src={object.maskUrl} alt="Object mask" /></div></div><div className="remote-result remote-result-3d">{createElement('model-viewer', { src: object.modelUrl, 'camera-controls': true, 'auto-rotate': true, 'shadow-intensity': '1', ar: '', 'aria-label': 'Generated 3D model' })}</div></>}</section>
}
