import { useEffect, useMemo, useState } from 'react'
import { getRemoteScanApiUrl, getRemoteScanJob, submitRemoteScan, type RemoteScanJob } from '../api/remoteScanService'
type Props = { frames: Blob[]; onClose: () => void }
type ViewMode = 'mask' | '3d'
export function RemoteScanPanel({ frames, onClose }: Props) {
  const [apiUrl, setApiUrl] = useState(getRemoteScanApiUrl()); const [job, setJob] = useState<RemoteScanJob | null>(null); const [mode, setMode] = useState<ViewMode>('mask'); const [selected, setSelected] = useState(0); const [error, setError] = useState<string | null>(null); const [sending, setSending] = useState(false)
  const object = job?.objects?.[selected]; const localPreview = useMemo(() => frames[selected] ? URL.createObjectURL(frames[selected]) : '', [frames, selected]); useEffect(() => () => { if (localPreview) URL.revokeObjectURL(localPreview) }, [localPreview])
  const send = async () => { setError(null); setSending(true); localStorage.setItem('cemetery.scanApiUrl', apiUrl); try { const { jobId } = await submitRemoteScan(frames, apiUrl); setJob({ jobId, status: 'queued', progress: 0 }) } catch (e) { setError(e instanceof Error ? e.message : 'Не удалось отправить кадры на ПК') } finally { setSending(false) } }
  useEffect(() => { if (!job || job.status === 'completed' || job.status === 'failed') return; const timer = window.setInterval(() => { void getRemoteScanJob(job.jobId, apiUrl).then(setJob).catch((e) => { setError(e instanceof Error ? e.message : 'Ошибка связи с ПК'); window.clearInterval(timer) }) }, 1500); return () => window.clearInterval(timer) }, [job, apiUrl])
  // @ts-ignore model-viewer is a web component and React's JSX types do not include it.
  return <section className="remote-scan-panel"><header><div><p className="scan-kicker">REMOTE PIPELINE</p><h2>PC reconstruction</h2></div><button className="remote-close" onClick={onClose}>Close</button></header>
    {!job && <><p className="remote-note">Кадров: {frames.length}. ПК выделит передний объект, построит приблизительный GLB и вернёт результат.</p><label className="remote-label">PC API URL<input value={apiUrl} onChange={(e) => setApiUrl(e.target.value)} placeholder="https://your-pc-tunnel.example" /></label><button className="remote-action" disabled={sending || frames.length === 0} onClick={() => void send()}>{sending ? 'Отправка…' : 'SEND TO PC'}</button></>}
    {job && <><p className="remote-note">{job.status === 'completed' ? `Готово: ${job.objects?.length ?? 0} результата(ов)` : job.status === 'failed' ? job.message || 'Ошибка обработки' : `Обработка на ПК: ${job.progress}%`}</p>{job.status === 'completed' && object && job.objects && <><div className="remote-tabs"><button className={mode === 'mask' ? 'active' : ''} onClick={() => setMode('mask')}>Camera + mask</button><button className={mode === '3d' ? 'active' : ''} onClick={() => setMode('3d')}>Pure 3D</button></div><div className={`remote-result remote-result-${mode}`}>{mode === 'mask' ? <div className="mask-preview"><img src={localPreview} alt="Captured frame" /><img className="mask-layer" src={object.maskUrl} alt="Detected object mask" /></div> : <model-viewer src={object.modelUrl} camera-controls auto-rotate shadow-intensity="1" ar="" aria-label="Generated 3D model" />}</div><div className="remote-frame-picker">{job.objects.map((item, index) => <button key={item.id} className={selected === index ? 'active' : ''} onClick={() => setSelected(index)}>#{index + 1}</button>)}</div></>}</>}</section>
}
